//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICalService")]
    public interface ICalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalService/Add", ReplyAction="http://tempuri.org/ICalService/AddResponse")]
        double Add(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalService/Add", ReplyAction="http://tempuri.org/ICalService/AddResponse")]
        System.Threading.Tasks.Task<double> AddAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalService/Sub", ReplyAction="http://tempuri.org/ICalService/SubResponse")]
        double Sub(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalService/Sub", ReplyAction="http://tempuri.org/ICalService/SubResponse")]
        System.Threading.Tasks.Task<double> SubAsync(double a, double b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalServiceChannel : Form2.ServiceReference1.ICalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalServiceClient : System.ServiceModel.ClientBase<Form2.ServiceReference1.ICalService>, Form2.ServiceReference1.ICalService {
        
        public CalServiceClient() {
        }
        
        public CalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Add(double a, double b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<double> AddAsync(double a, double b) {
            return base.Channel.AddAsync(a, b);
        }
        
        public double Sub(double a, double b) {
            return base.Channel.Sub(a, b);
        }
        
        public System.Threading.Tasks.Task<double> SubAsync(double a, double b) {
            return base.Channel.SubAsync(a, b);
        }
    }
}
